/*
Solanabeach Backend API

Solanabeach Backend REST API documentation.  ## Rate limiting Current API rate limit per IP is 100 requests per second.    ## Pagination Most of the endpoints returning array data support pagination. The API uses two types of pagination, depending on the returned data. Some endpoints support both, some are limited to just one type.    ## Supported pagination types ### Offset / limit Offset / limit pagination is the simplest form of pagination supported by the API. Offset parameter represents the number of results to skip before returning the data, and the limit parameter limits the number of returned results.   To prevent overloading the API, all limit params have a max value. Each API endpoint has its own max value.  ### Cursor Cursor pagination is more complex than the offset / limit one, but, it comes naturally for some blockchain data (such as blocks, transactions, token transfers, etc). Cursors contain data like blocknumber, transaction index, ... and they're described on their respective API endpoints. Limit parameter works exactly the same way as it does in the offset / limit pagination.  ## Authentication The public API uses a Bearer OAuth authentication method, and the API key should be provided in the `Authorization` header in each request. API keys are issued on request. 

API version: 0.0.1
Contact: andrej@vgng.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AccountSwapInstructionTokenswap struct for AccountSwapInstructionTokenswap
type AccountSwapInstructionTokenswap struct {
	Pubkey *Address `json:"pubkey,omitempty"`
	Name *string `json:"name,omitempty"`
	TokenA *AccountSwapInstructionTokenswapTokenA `json:"tokenA,omitempty"`
	TokenB *AccountSwapInstructionTokenswapTokenA `json:"tokenB,omitempty"`
	PoolToken *AccountSwapInstructionTokenswapPoolToken `json:"poolToken,omitempty"`
}

// NewAccountSwapInstructionTokenswap instantiates a new AccountSwapInstructionTokenswap object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountSwapInstructionTokenswap() *AccountSwapInstructionTokenswap {
	this := AccountSwapInstructionTokenswap{}
	return &this
}

// NewAccountSwapInstructionTokenswapWithDefaults instantiates a new AccountSwapInstructionTokenswap object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountSwapInstructionTokenswapWithDefaults() *AccountSwapInstructionTokenswap {
	this := AccountSwapInstructionTokenswap{}
	return &this
}

// GetPubkey returns the Pubkey field value if set, zero value otherwise.
func (o *AccountSwapInstructionTokenswap) GetPubkey() Address {
	if o == nil || o.Pubkey == nil {
		var ret Address
		return ret
	}
	return *o.Pubkey
}

// GetPubkeyOk returns a tuple with the Pubkey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountSwapInstructionTokenswap) GetPubkeyOk() (*Address, bool) {
	if o == nil || o.Pubkey == nil {
		return nil, false
	}
	return o.Pubkey, true
}

// HasPubkey returns a boolean if a field has been set.
func (o *AccountSwapInstructionTokenswap) HasPubkey() bool {
	if o != nil && o.Pubkey != nil {
		return true
	}

	return false
}

// SetPubkey gets a reference to the given Address and assigns it to the Pubkey field.
func (o *AccountSwapInstructionTokenswap) SetPubkey(v Address) {
	o.Pubkey = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AccountSwapInstructionTokenswap) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountSwapInstructionTokenswap) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AccountSwapInstructionTokenswap) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AccountSwapInstructionTokenswap) SetName(v string) {
	o.Name = &v
}

// GetTokenA returns the TokenA field value if set, zero value otherwise.
func (o *AccountSwapInstructionTokenswap) GetTokenA() AccountSwapInstructionTokenswapTokenA {
	if o == nil || o.TokenA == nil {
		var ret AccountSwapInstructionTokenswapTokenA
		return ret
	}
	return *o.TokenA
}

// GetTokenAOk returns a tuple with the TokenA field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountSwapInstructionTokenswap) GetTokenAOk() (*AccountSwapInstructionTokenswapTokenA, bool) {
	if o == nil || o.TokenA == nil {
		return nil, false
	}
	return o.TokenA, true
}

// HasTokenA returns a boolean if a field has been set.
func (o *AccountSwapInstructionTokenswap) HasTokenA() bool {
	if o != nil && o.TokenA != nil {
		return true
	}

	return false
}

// SetTokenA gets a reference to the given AccountSwapInstructionTokenswapTokenA and assigns it to the TokenA field.
func (o *AccountSwapInstructionTokenswap) SetTokenA(v AccountSwapInstructionTokenswapTokenA) {
	o.TokenA = &v
}

// GetTokenB returns the TokenB field value if set, zero value otherwise.
func (o *AccountSwapInstructionTokenswap) GetTokenB() AccountSwapInstructionTokenswapTokenA {
	if o == nil || o.TokenB == nil {
		var ret AccountSwapInstructionTokenswapTokenA
		return ret
	}
	return *o.TokenB
}

// GetTokenBOk returns a tuple with the TokenB field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountSwapInstructionTokenswap) GetTokenBOk() (*AccountSwapInstructionTokenswapTokenA, bool) {
	if o == nil || o.TokenB == nil {
		return nil, false
	}
	return o.TokenB, true
}

// HasTokenB returns a boolean if a field has been set.
func (o *AccountSwapInstructionTokenswap) HasTokenB() bool {
	if o != nil && o.TokenB != nil {
		return true
	}

	return false
}

// SetTokenB gets a reference to the given AccountSwapInstructionTokenswapTokenA and assigns it to the TokenB field.
func (o *AccountSwapInstructionTokenswap) SetTokenB(v AccountSwapInstructionTokenswapTokenA) {
	o.TokenB = &v
}

// GetPoolToken returns the PoolToken field value if set, zero value otherwise.
func (o *AccountSwapInstructionTokenswap) GetPoolToken() AccountSwapInstructionTokenswapPoolToken {
	if o == nil || o.PoolToken == nil {
		var ret AccountSwapInstructionTokenswapPoolToken
		return ret
	}
	return *o.PoolToken
}

// GetPoolTokenOk returns a tuple with the PoolToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountSwapInstructionTokenswap) GetPoolTokenOk() (*AccountSwapInstructionTokenswapPoolToken, bool) {
	if o == nil || o.PoolToken == nil {
		return nil, false
	}
	return o.PoolToken, true
}

// HasPoolToken returns a boolean if a field has been set.
func (o *AccountSwapInstructionTokenswap) HasPoolToken() bool {
	if o != nil && o.PoolToken != nil {
		return true
	}

	return false
}

// SetPoolToken gets a reference to the given AccountSwapInstructionTokenswapPoolToken and assigns it to the PoolToken field.
func (o *AccountSwapInstructionTokenswap) SetPoolToken(v AccountSwapInstructionTokenswapPoolToken) {
	o.PoolToken = &v
}

func (o AccountSwapInstructionTokenswap) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Pubkey != nil {
		toSerialize["pubkey"] = o.Pubkey
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.TokenA != nil {
		toSerialize["tokenA"] = o.TokenA
	}
	if o.TokenB != nil {
		toSerialize["tokenB"] = o.TokenB
	}
	if o.PoolToken != nil {
		toSerialize["poolToken"] = o.PoolToken
	}
	return json.Marshal(toSerialize)
}

type NullableAccountSwapInstructionTokenswap struct {
	value *AccountSwapInstructionTokenswap
	isSet bool
}

func (v NullableAccountSwapInstructionTokenswap) Get() *AccountSwapInstructionTokenswap {
	return v.value
}

func (v *NullableAccountSwapInstructionTokenswap) Set(val *AccountSwapInstructionTokenswap) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountSwapInstructionTokenswap) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountSwapInstructionTokenswap) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountSwapInstructionTokenswap(val *AccountSwapInstructionTokenswap) *NullableAccountSwapInstructionTokenswap {
	return &NullableAccountSwapInstructionTokenswap{value: val, isSet: true}
}

func (v NullableAccountSwapInstructionTokenswap) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountSwapInstructionTokenswap) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


