/*
Solanabeach Backend API

Solanabeach Backend REST API documentation.  ## Rate limiting Current API rate limit per IP is 100 requests per second.    ## Pagination Most of the endpoints returning array data support pagination. The API uses two types of pagination, depending on the returned data. Some endpoints support both, some are limited to just one type.    ## Supported pagination types ### Offset / limit Offset / limit pagination is the simplest form of pagination supported by the API. Offset parameter represents the number of results to skip before returning the data, and the limit parameter limits the number of returned results.   To prevent overloading the API, all limit params have a max value. Each API endpoint has its own max value.  ### Cursor Cursor pagination is more complex than the offset / limit one, but, it comes naturally for some blockchain data (such as blocks, transactions, token transfers, etc). Cursors contain data like blocknumber, transaction index, ... and they're described on their respective API endpoints. Limit parameter works exactly the same way as it does in the offset / limit pagination.  ## Authentication The public API uses a Bearer OAuth authentication method, and the API key should be provided in the `Authorization` header in each request. API keys are issued on request. 

API version: 0.0.1
Contact: andrej@vgng.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// StakeAccount struct for StakeAccount
type StakeAccount struct {
	Pubkey *string `json:"pubkey,omitempty"`
	Lamports *int64 `json:"lamports,omitempty"`
	Data *StakeAccountData `json:"data,omitempty"`
}

// NewStakeAccount instantiates a new StakeAccount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStakeAccount() *StakeAccount {
	this := StakeAccount{}
	return &this
}

// NewStakeAccountWithDefaults instantiates a new StakeAccount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStakeAccountWithDefaults() *StakeAccount {
	this := StakeAccount{}
	return &this
}

// GetPubkey returns the Pubkey field value if set, zero value otherwise.
func (o *StakeAccount) GetPubkey() string {
	if o == nil || o.Pubkey == nil {
		var ret string
		return ret
	}
	return *o.Pubkey
}

// GetPubkeyOk returns a tuple with the Pubkey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StakeAccount) GetPubkeyOk() (*string, bool) {
	if o == nil || o.Pubkey == nil {
		return nil, false
	}
	return o.Pubkey, true
}

// HasPubkey returns a boolean if a field has been set.
func (o *StakeAccount) HasPubkey() bool {
	if o != nil && o.Pubkey != nil {
		return true
	}

	return false
}

// SetPubkey gets a reference to the given string and assigns it to the Pubkey field.
func (o *StakeAccount) SetPubkey(v string) {
	o.Pubkey = &v
}

// GetLamports returns the Lamports field value if set, zero value otherwise.
func (o *StakeAccount) GetLamports() int64 {
	if o == nil || o.Lamports == nil {
		var ret int64
		return ret
	}
	return *o.Lamports
}

// GetLamportsOk returns a tuple with the Lamports field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StakeAccount) GetLamportsOk() (*int64, bool) {
	if o == nil || o.Lamports == nil {
		return nil, false
	}
	return o.Lamports, true
}

// HasLamports returns a boolean if a field has been set.
func (o *StakeAccount) HasLamports() bool {
	if o != nil && o.Lamports != nil {
		return true
	}

	return false
}

// SetLamports gets a reference to the given int64 and assigns it to the Lamports field.
func (o *StakeAccount) SetLamports(v int64) {
	o.Lamports = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *StakeAccount) GetData() StakeAccountData {
	if o == nil || o.Data == nil {
		var ret StakeAccountData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StakeAccount) GetDataOk() (*StakeAccountData, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *StakeAccount) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given StakeAccountData and assigns it to the Data field.
func (o *StakeAccount) SetData(v StakeAccountData) {
	o.Data = &v
}

func (o StakeAccount) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Pubkey != nil {
		toSerialize["pubkey"] = o.Pubkey
	}
	if o.Lamports != nil {
		toSerialize["lamports"] = o.Lamports
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableStakeAccount struct {
	value *StakeAccount
	isSet bool
}

func (v NullableStakeAccount) Get() *StakeAccount {
	return v.value
}

func (v *NullableStakeAccount) Set(val *StakeAccount) {
	v.value = val
	v.isSet = true
}

func (v NullableStakeAccount) IsSet() bool {
	return v.isSet
}

func (v *NullableStakeAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStakeAccount(val *StakeAccount) *NullableStakeAccount {
	return &NullableStakeAccount{value: val, isSet: true}
}

func (v NullableStakeAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStakeAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


