/*
Solanabeach Backend API

Solanabeach Backend REST API documentation.  ## Rate limiting Current API rate limit per IP is 100 requests per second.    ## Pagination Most of the endpoints returning array data support pagination. The API uses two types of pagination, depending on the returned data. Some endpoints support both, some are limited to just one type.    ## Supported pagination types ### Offset / limit Offset / limit pagination is the simplest form of pagination supported by the API. Offset parameter represents the number of results to skip before returning the data, and the limit parameter limits the number of returned results.   To prevent overloading the API, all limit params have a max value. Each API endpoint has its own max value.  ### Cursor Cursor pagination is more complex than the offset / limit one, but, it comes naturally for some blockchain data (such as blocks, transactions, token transfers, etc). Cursors contain data like blocknumber, transaction index, ... and they're described on their respective API endpoints. Limit parameter works exactly the same way as it does in the offset / limit pagination.  ## Authentication The public API uses a Bearer OAuth authentication method, and the API key should be provided in the `Authorization` header in each request. API keys are issued on request. 

API version: 0.0.1
Contact: andrej@vgng.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// StakeAccountDataMeta struct for StakeAccountDataMeta
type StakeAccountDataMeta struct {
	RentExemptReserve *int32 `json:"rent_exempt_reserve,omitempty"`
	Authorized *StakeAccountDataMetaAuthorized `json:"authorized,omitempty"`
}

// NewStakeAccountDataMeta instantiates a new StakeAccountDataMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStakeAccountDataMeta() *StakeAccountDataMeta {
	this := StakeAccountDataMeta{}
	return &this
}

// NewStakeAccountDataMetaWithDefaults instantiates a new StakeAccountDataMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStakeAccountDataMetaWithDefaults() *StakeAccountDataMeta {
	this := StakeAccountDataMeta{}
	return &this
}

// GetRentExemptReserve returns the RentExemptReserve field value if set, zero value otherwise.
func (o *StakeAccountDataMeta) GetRentExemptReserve() int32 {
	if o == nil || o.RentExemptReserve == nil {
		var ret int32
		return ret
	}
	return *o.RentExemptReserve
}

// GetRentExemptReserveOk returns a tuple with the RentExemptReserve field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StakeAccountDataMeta) GetRentExemptReserveOk() (*int32, bool) {
	if o == nil || o.RentExemptReserve == nil {
		return nil, false
	}
	return o.RentExemptReserve, true
}

// HasRentExemptReserve returns a boolean if a field has been set.
func (o *StakeAccountDataMeta) HasRentExemptReserve() bool {
	if o != nil && o.RentExemptReserve != nil {
		return true
	}

	return false
}

// SetRentExemptReserve gets a reference to the given int32 and assigns it to the RentExemptReserve field.
func (o *StakeAccountDataMeta) SetRentExemptReserve(v int32) {
	o.RentExemptReserve = &v
}

// GetAuthorized returns the Authorized field value if set, zero value otherwise.
func (o *StakeAccountDataMeta) GetAuthorized() StakeAccountDataMetaAuthorized {
	if o == nil || o.Authorized == nil {
		var ret StakeAccountDataMetaAuthorized
		return ret
	}
	return *o.Authorized
}

// GetAuthorizedOk returns a tuple with the Authorized field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StakeAccountDataMeta) GetAuthorizedOk() (*StakeAccountDataMetaAuthorized, bool) {
	if o == nil || o.Authorized == nil {
		return nil, false
	}
	return o.Authorized, true
}

// HasAuthorized returns a boolean if a field has been set.
func (o *StakeAccountDataMeta) HasAuthorized() bool {
	if o != nil && o.Authorized != nil {
		return true
	}

	return false
}

// SetAuthorized gets a reference to the given StakeAccountDataMetaAuthorized and assigns it to the Authorized field.
func (o *StakeAccountDataMeta) SetAuthorized(v StakeAccountDataMetaAuthorized) {
	o.Authorized = &v
}

func (o StakeAccountDataMeta) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.RentExemptReserve != nil {
		toSerialize["rent_exempt_reserve"] = o.RentExemptReserve
	}
	if o.Authorized != nil {
		toSerialize["authorized"] = o.Authorized
	}
	return json.Marshal(toSerialize)
}

type NullableStakeAccountDataMeta struct {
	value *StakeAccountDataMeta
	isSet bool
}

func (v NullableStakeAccountDataMeta) Get() *StakeAccountDataMeta {
	return v.value
}

func (v *NullableStakeAccountDataMeta) Set(val *StakeAccountDataMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableStakeAccountDataMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableStakeAccountDataMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStakeAccountDataMeta(val *StakeAccountDataMeta) *NullableStakeAccountDataMeta {
	return &NullableStakeAccountDataMeta{value: val, isSet: true}
}

func (v NullableStakeAccountDataMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStakeAccountDataMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


