/*
Solanabeach Backend API

Solanabeach Backend REST API documentation.  ## Rate limiting Current API rate limit per IP is 100 requests per second.    ## Pagination Most of the endpoints returning array data support pagination. The API uses two types of pagination, depending on the returned data. Some endpoints support both, some are limited to just one type.    ## Supported pagination types ### Offset / limit Offset / limit pagination is the simplest form of pagination supported by the API. Offset parameter represents the number of results to skip before returning the data, and the limit parameter limits the number of returned results.   To prevent overloading the API, all limit params have a max value. Each API endpoint has its own max value.  ### Cursor Cursor pagination is more complex than the offset / limit one, but, it comes naturally for some blockchain data (such as blocks, transactions, token transfers, etc). Cursors contain data like blocknumber, transaction index, ... and they're described on their respective API endpoints. Limit parameter works exactly the same way as it does in the offset / limit pagination.  ## Authentication The public API uses a Bearer OAuth authentication method, and the API key should be provided in the `Authorization` header in each request. API keys are issued on request. 

API version: 0.0.1
Contact: andrej@vgng.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ValidatorValidatorAsn struct for ValidatorValidatorAsn
type ValidatorValidatorAsn struct {
	Code *string `json:"code,omitempty"`
	Organization *string `json:"organization,omitempty"`
}

// NewValidatorValidatorAsn instantiates a new ValidatorValidatorAsn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValidatorValidatorAsn() *ValidatorValidatorAsn {
	this := ValidatorValidatorAsn{}
	return &this
}

// NewValidatorValidatorAsnWithDefaults instantiates a new ValidatorValidatorAsn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValidatorValidatorAsnWithDefaults() *ValidatorValidatorAsn {
	this := ValidatorValidatorAsn{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *ValidatorValidatorAsn) GetCode() string {
	if o == nil || o.Code == nil {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidatorValidatorAsn) GetCodeOk() (*string, bool) {
	if o == nil || o.Code == nil {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *ValidatorValidatorAsn) HasCode() bool {
	if o != nil && o.Code != nil {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *ValidatorValidatorAsn) SetCode(v string) {
	o.Code = &v
}

// GetOrganization returns the Organization field value if set, zero value otherwise.
func (o *ValidatorValidatorAsn) GetOrganization() string {
	if o == nil || o.Organization == nil {
		var ret string
		return ret
	}
	return *o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidatorValidatorAsn) GetOrganizationOk() (*string, bool) {
	if o == nil || o.Organization == nil {
		return nil, false
	}
	return o.Organization, true
}

// HasOrganization returns a boolean if a field has been set.
func (o *ValidatorValidatorAsn) HasOrganization() bool {
	if o != nil && o.Organization != nil {
		return true
	}

	return false
}

// SetOrganization gets a reference to the given string and assigns it to the Organization field.
func (o *ValidatorValidatorAsn) SetOrganization(v string) {
	o.Organization = &v
}

func (o ValidatorValidatorAsn) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Code != nil {
		toSerialize["code"] = o.Code
	}
	if o.Organization != nil {
		toSerialize["organization"] = o.Organization
	}
	return json.Marshal(toSerialize)
}

type NullableValidatorValidatorAsn struct {
	value *ValidatorValidatorAsn
	isSet bool
}

func (v NullableValidatorValidatorAsn) Get() *ValidatorValidatorAsn {
	return v.value
}

func (v *NullableValidatorValidatorAsn) Set(val *ValidatorValidatorAsn) {
	v.value = val
	v.isSet = true
}

func (v NullableValidatorValidatorAsn) IsSet() bool {
	return v.isSet
}

func (v *NullableValidatorValidatorAsn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValidatorValidatorAsn(val *ValidatorValidatorAsn) *NullableValidatorValidatorAsn {
	return &NullableValidatorValidatorAsn{value: val, isSet: true}
}

func (v NullableValidatorValidatorAsn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValidatorValidatorAsn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


