/*
Solanabeach Backend API

Solanabeach Backend REST API documentation.  ## Rate limiting Current API rate limit per IP is 100 requests per second.    ## Pagination Most of the endpoints returning array data support pagination. The API uses two types of pagination, depending on the returned data. Some endpoints support both, some are limited to just one type.    ## Supported pagination types ### Offset / limit Offset / limit pagination is the simplest form of pagination supported by the API. Offset parameter represents the number of results to skip before returning the data, and the limit parameter limits the number of returned results.   To prevent overloading the API, all limit params have a max value. Each API endpoint has its own max value.  ### Cursor Cursor pagination is more complex than the offset / limit one, but, it comes naturally for some blockchain data (such as blocks, transactions, token transfers, etc). Cursors contain data like blocknumber, transaction index, ... and they're described on their respective API endpoints. Limit parameter works exactly the same way as it does in the offset / limit pagination.  ## Authentication The public API uses a Bearer OAuth authentication method, and the API key should be provided in the `Authorization` header in each request. API keys are issued on request. 

API version: 0.0.1
Contact: andrej@vgng.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// BlockProgramstats struct for BlockProgramstats
type BlockProgramstats struct {
	Count *int32 `json:"count,omitempty"`
	ProgramId *Address `json:"programId,omitempty"`
	Instructions *map[string]interface{} `json:"instructions,omitempty"`
}

// NewBlockProgramstats instantiates a new BlockProgramstats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBlockProgramstats() *BlockProgramstats {
	this := BlockProgramstats{}
	return &this
}

// NewBlockProgramstatsWithDefaults instantiates a new BlockProgramstats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBlockProgramstatsWithDefaults() *BlockProgramstats {
	this := BlockProgramstats{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *BlockProgramstats) GetCount() int32 {
	if o == nil || o.Count == nil {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlockProgramstats) GetCountOk() (*int32, bool) {
	if o == nil || o.Count == nil {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *BlockProgramstats) HasCount() bool {
	if o != nil && o.Count != nil {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *BlockProgramstats) SetCount(v int32) {
	o.Count = &v
}

// GetProgramId returns the ProgramId field value if set, zero value otherwise.
func (o *BlockProgramstats) GetProgramId() Address {
	if o == nil || o.ProgramId == nil {
		var ret Address
		return ret
	}
	return *o.ProgramId
}

// GetProgramIdOk returns a tuple with the ProgramId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlockProgramstats) GetProgramIdOk() (*Address, bool) {
	if o == nil || o.ProgramId == nil {
		return nil, false
	}
	return o.ProgramId, true
}

// HasProgramId returns a boolean if a field has been set.
func (o *BlockProgramstats) HasProgramId() bool {
	if o != nil && o.ProgramId != nil {
		return true
	}

	return false
}

// SetProgramId gets a reference to the given Address and assigns it to the ProgramId field.
func (o *BlockProgramstats) SetProgramId(v Address) {
	o.ProgramId = &v
}

// GetInstructions returns the Instructions field value if set, zero value otherwise.
func (o *BlockProgramstats) GetInstructions() map[string]interface{} {
	if o == nil || o.Instructions == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.Instructions
}

// GetInstructionsOk returns a tuple with the Instructions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlockProgramstats) GetInstructionsOk() (*map[string]interface{}, bool) {
	if o == nil || o.Instructions == nil {
		return nil, false
	}
	return o.Instructions, true
}

// HasInstructions returns a boolean if a field has been set.
func (o *BlockProgramstats) HasInstructions() bool {
	if o != nil && o.Instructions != nil {
		return true
	}

	return false
}

// SetInstructions gets a reference to the given map[string]interface{} and assigns it to the Instructions field.
func (o *BlockProgramstats) SetInstructions(v map[string]interface{}) {
	o.Instructions = &v
}

func (o BlockProgramstats) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Count != nil {
		toSerialize["count"] = o.Count
	}
	if o.ProgramId != nil {
		toSerialize["programId"] = o.ProgramId
	}
	if o.Instructions != nil {
		toSerialize["instructions"] = o.Instructions
	}
	return json.Marshal(toSerialize)
}

type NullableBlockProgramstats struct {
	value *BlockProgramstats
	isSet bool
}

func (v NullableBlockProgramstats) Get() *BlockProgramstats {
	return v.value
}

func (v *NullableBlockProgramstats) Set(val *BlockProgramstats) {
	v.value = val
	v.isSet = true
}

func (v NullableBlockProgramstats) IsSet() bool {
	return v.isSet
}

func (v *NullableBlockProgramstats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlockProgramstats(val *BlockProgramstats) *NullableBlockProgramstats {
	return &NullableBlockProgramstats{value: val, isSet: true}
}

func (v NullableBlockProgramstats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlockProgramstats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


