/*
Solanabeach Backend API

Solanabeach Backend REST API documentation.  ## Rate limiting Current API rate limit per IP is 100 requests per second.    ## Pagination Most of the endpoints returning array data support pagination. The API uses two types of pagination, depending on the returned data. Some endpoints support both, some are limited to just one type.    ## Supported pagination types ### Offset / limit Offset / limit pagination is the simplest form of pagination supported by the API. Offset parameter represents the number of results to skip before returning the data, and the limit parameter limits the number of returned results.   To prevent overloading the API, all limit params have a max value. Each API endpoint has its own max value.  ### Cursor Cursor pagination is more complex than the offset / limit one, but, it comes naturally for some blockchain data (such as blocks, transactions, token transfers, etc). Cursors contain data like blocknumber, transaction index, ... and they're described on their respective API endpoints. Limit parameter works exactly the same way as it does in the offset / limit pagination.  ## Authentication The public API uses a Bearer OAuth authentication method, and the API key should be provided in the `Authorization` header in each request. API keys are issued on request. 

API version: 0.0.1
Contact: andrej@vgng.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SimpleAccount struct for SimpleAccount
type SimpleAccount struct {
	Pubkey *Address `json:"pubkey,omitempty"`
	Balance *int32 `json:"balance,omitempty"`
}

// NewSimpleAccount instantiates a new SimpleAccount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSimpleAccount() *SimpleAccount {
	this := SimpleAccount{}
	return &this
}

// NewSimpleAccountWithDefaults instantiates a new SimpleAccount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSimpleAccountWithDefaults() *SimpleAccount {
	this := SimpleAccount{}
	return &this
}

// GetPubkey returns the Pubkey field value if set, zero value otherwise.
func (o *SimpleAccount) GetPubkey() Address {
	if o == nil || o.Pubkey == nil {
		var ret Address
		return ret
	}
	return *o.Pubkey
}

// GetPubkeyOk returns a tuple with the Pubkey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SimpleAccount) GetPubkeyOk() (*Address, bool) {
	if o == nil || o.Pubkey == nil {
		return nil, false
	}
	return o.Pubkey, true
}

// HasPubkey returns a boolean if a field has been set.
func (o *SimpleAccount) HasPubkey() bool {
	if o != nil && o.Pubkey != nil {
		return true
	}

	return false
}

// SetPubkey gets a reference to the given Address and assigns it to the Pubkey field.
func (o *SimpleAccount) SetPubkey(v Address) {
	o.Pubkey = &v
}

// GetBalance returns the Balance field value if set, zero value otherwise.
func (o *SimpleAccount) GetBalance() int32 {
	if o == nil || o.Balance == nil {
		var ret int32
		return ret
	}
	return *o.Balance
}

// GetBalanceOk returns a tuple with the Balance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SimpleAccount) GetBalanceOk() (*int32, bool) {
	if o == nil || o.Balance == nil {
		return nil, false
	}
	return o.Balance, true
}

// HasBalance returns a boolean if a field has been set.
func (o *SimpleAccount) HasBalance() bool {
	if o != nil && o.Balance != nil {
		return true
	}

	return false
}

// SetBalance gets a reference to the given int32 and assigns it to the Balance field.
func (o *SimpleAccount) SetBalance(v int32) {
	o.Balance = &v
}

func (o SimpleAccount) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Pubkey != nil {
		toSerialize["pubkey"] = o.Pubkey
	}
	if o.Balance != nil {
		toSerialize["balance"] = o.Balance
	}
	return json.Marshal(toSerialize)
}

type NullableSimpleAccount struct {
	value *SimpleAccount
	isSet bool
}

func (v NullableSimpleAccount) Get() *SimpleAccount {
	return v.value
}

func (v *NullableSimpleAccount) Set(val *SimpleAccount) {
	v.value = val
	v.isSet = true
}

func (v NullableSimpleAccount) IsSet() bool {
	return v.isSet
}

func (v *NullableSimpleAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSimpleAccount(val *SimpleAccount) *NullableSimpleAccount {
	return &NullableSimpleAccount{value: val, isSet: true}
}

func (v NullableSimpleAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSimpleAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


