/*
Solanabeach Backend API

Solanabeach Backend REST API documentation.  ## Rate limiting Current API rate limit per IP is 100 requests per second.    ## Pagination Most of the endpoints returning array data support pagination. The API uses two types of pagination, depending on the returned data. Some endpoints support both, some are limited to just one type.    ## Supported pagination types ### Offset / limit Offset / limit pagination is the simplest form of pagination supported by the API. Offset parameter represents the number of results to skip before returning the data, and the limit parameter limits the number of returned results.   To prevent overloading the API, all limit params have a max value. Each API endpoint has its own max value.  ### Cursor Cursor pagination is more complex than the offset / limit one, but, it comes naturally for some blockchain data (such as blocks, transactions, token transfers, etc). Cursors contain data like blocknumber, transaction index, ... and they're described on their respective API endpoints. Limit parameter works exactly the same way as it does in the offset / limit pagination.  ## Authentication The public API uses a Bearer OAuth authentication method, and the API key should be provided in the `Authorization` header in each request. API keys are issued on request. 

API version: 0.0.1
Contact: andrej@vgng.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// Wealth struct for Wealth
type Wealth struct {
	Wealth *WealthWealth `json:"wealth,omitempty"`
}

// NewWealth instantiates a new Wealth object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWealth() *Wealth {
	this := Wealth{}
	return &this
}

// NewWealthWithDefaults instantiates a new Wealth object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWealthWithDefaults() *Wealth {
	this := Wealth{}
	return &this
}

// GetWealth returns the Wealth field value if set, zero value otherwise.
func (o *Wealth) GetWealth() WealthWealth {
	if o == nil || o.Wealth == nil {
		var ret WealthWealth
		return ret
	}
	return *o.Wealth
}

// GetWealthOk returns a tuple with the Wealth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Wealth) GetWealthOk() (*WealthWealth, bool) {
	if o == nil || o.Wealth == nil {
		return nil, false
	}
	return o.Wealth, true
}

// HasWealth returns a boolean if a field has been set.
func (o *Wealth) HasWealth() bool {
	if o != nil && o.Wealth != nil {
		return true
	}

	return false
}

// SetWealth gets a reference to the given WealthWealth and assigns it to the Wealth field.
func (o *Wealth) SetWealth(v WealthWealth) {
	o.Wealth = &v
}

func (o Wealth) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Wealth != nil {
		toSerialize["wealth"] = o.Wealth
	}
	return json.Marshal(toSerialize)
}

type NullableWealth struct {
	value *Wealth
	isSet bool
}

func (v NullableWealth) Get() *Wealth {
	return v.value
}

func (v *NullableWealth) Set(val *Wealth) {
	v.value = val
	v.isSet = true
}

func (v NullableWealth) IsSet() bool {
	return v.isSet
}

func (v *NullableWealth) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWealth(val *Wealth) *NullableWealth {
	return &NullableWealth{value: val, isSet: true}
}

func (v NullableWealth) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWealth) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


