/*
Solanabeach Backend API

Solanabeach Backend REST API documentation.  ## Rate limiting Current API rate limit per IP is 100 requests per second.    ## Pagination Most of the endpoints returning array data support pagination. The API uses two types of pagination, depending on the returned data. Some endpoints support both, some are limited to just one type.    ## Supported pagination types ### Offset / limit Offset / limit pagination is the simplest form of pagination supported by the API. Offset parameter represents the number of results to skip before returning the data, and the limit parameter limits the number of returned results.   To prevent overloading the API, all limit params have a max value. Each API endpoint has its own max value.  ### Cursor Cursor pagination is more complex than the offset / limit one, but, it comes naturally for some blockchain data (such as blocks, transactions, token transfers, etc). Cursors contain data like blocknumber, transaction index, ... and they're described on their respective API endpoints. Limit parameter works exactly the same way as it does in the offset / limit pagination.  ## Authentication The public API uses a Bearer OAuth authentication method, and the API key should be provided in the `Authorization` header in each request. API keys are issued on request. 

API version: 0.0.1
Contact: andrej@vgng.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// TransactionInstructions struct for TransactionInstructions
type TransactionInstructions struct {
	// Depends on the type of instruction
	Parsed *map[string]interface{} `json:"parsed,omitempty"`
	Raw *TransactionRaw `json:"raw,omitempty"`
}

// NewTransactionInstructions instantiates a new TransactionInstructions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionInstructions() *TransactionInstructions {
	this := TransactionInstructions{}
	return &this
}

// NewTransactionInstructionsWithDefaults instantiates a new TransactionInstructions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionInstructionsWithDefaults() *TransactionInstructions {
	this := TransactionInstructions{}
	return &this
}

// GetParsed returns the Parsed field value if set, zero value otherwise.
func (o *TransactionInstructions) GetParsed() map[string]interface{} {
	if o == nil || o.Parsed == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.Parsed
}

// GetParsedOk returns a tuple with the Parsed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionInstructions) GetParsedOk() (*map[string]interface{}, bool) {
	if o == nil || o.Parsed == nil {
		return nil, false
	}
	return o.Parsed, true
}

// HasParsed returns a boolean if a field has been set.
func (o *TransactionInstructions) HasParsed() bool {
	if o != nil && o.Parsed != nil {
		return true
	}

	return false
}

// SetParsed gets a reference to the given map[string]interface{} and assigns it to the Parsed field.
func (o *TransactionInstructions) SetParsed(v map[string]interface{}) {
	o.Parsed = &v
}

// GetRaw returns the Raw field value if set, zero value otherwise.
func (o *TransactionInstructions) GetRaw() TransactionRaw {
	if o == nil || o.Raw == nil {
		var ret TransactionRaw
		return ret
	}
	return *o.Raw
}

// GetRawOk returns a tuple with the Raw field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionInstructions) GetRawOk() (*TransactionRaw, bool) {
	if o == nil || o.Raw == nil {
		return nil, false
	}
	return o.Raw, true
}

// HasRaw returns a boolean if a field has been set.
func (o *TransactionInstructions) HasRaw() bool {
	if o != nil && o.Raw != nil {
		return true
	}

	return false
}

// SetRaw gets a reference to the given TransactionRaw and assigns it to the Raw field.
func (o *TransactionInstructions) SetRaw(v TransactionRaw) {
	o.Raw = &v
}

func (o TransactionInstructions) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Parsed != nil {
		toSerialize["parsed"] = o.Parsed
	}
	if o.Raw != nil {
		toSerialize["raw"] = o.Raw
	}
	return json.Marshal(toSerialize)
}

type NullableTransactionInstructions struct {
	value *TransactionInstructions
	isSet bool
}

func (v NullableTransactionInstructions) Get() *TransactionInstructions {
	return v.value
}

func (v *NullableTransactionInstructions) Set(val *TransactionInstructions) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionInstructions) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionInstructions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionInstructions(val *TransactionInstructions) *NullableTransactionInstructions {
	return &NullableTransactionInstructions{value: val, isSet: true}
}

func (v NullableTransactionInstructions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionInstructions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


