/*
Solanabeach Backend API

Solanabeach Backend REST API documentation.  ## Rate limiting Current API rate limit per IP is 100 requests per second.    ## Pagination Most of the endpoints returning array data support pagination. The API uses two types of pagination, depending on the returned data. Some endpoints support both, some are limited to just one type.    ## Supported pagination types ### Offset / limit Offset / limit pagination is the simplest form of pagination supported by the API. Offset parameter represents the number of results to skip before returning the data, and the limit parameter limits the number of returned results.   To prevent overloading the API, all limit params have a max value. Each API endpoint has its own max value.  ### Cursor Cursor pagination is more complex than the offset / limit one, but, it comes naturally for some blockchain data (such as blocks, transactions, token transfers, etc). Cursors contain data like blocknumber, transaction index, ... and they're described on their respective API endpoints. Limit parameter works exactly the same way as it does in the offset / limit pagination.  ## Authentication The public API uses a Bearer OAuth authentication method, and the API key should be provided in the `Authorization` header in each request. API keys are issued on request. 

API version: 0.0.1
Contact: andrej@vgng.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// WealthWealthDistributionTotal struct for WealthWealthDistributionTotal
type WealthWealthDistributionTotal struct {
	System *string `json:"system,omitempty"`
	Stake *string `json:"stake,omitempty"`
	Spl *string `json:"spl,omitempty"`
	Sum *string `json:"sum,omitempty"`
}

// NewWealthWealthDistributionTotal instantiates a new WealthWealthDistributionTotal object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWealthWealthDistributionTotal() *WealthWealthDistributionTotal {
	this := WealthWealthDistributionTotal{}
	return &this
}

// NewWealthWealthDistributionTotalWithDefaults instantiates a new WealthWealthDistributionTotal object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWealthWealthDistributionTotalWithDefaults() *WealthWealthDistributionTotal {
	this := WealthWealthDistributionTotal{}
	return &this
}

// GetSystem returns the System field value if set, zero value otherwise.
func (o *WealthWealthDistributionTotal) GetSystem() string {
	if o == nil || o.System == nil {
		var ret string
		return ret
	}
	return *o.System
}

// GetSystemOk returns a tuple with the System field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WealthWealthDistributionTotal) GetSystemOk() (*string, bool) {
	if o == nil || o.System == nil {
		return nil, false
	}
	return o.System, true
}

// HasSystem returns a boolean if a field has been set.
func (o *WealthWealthDistributionTotal) HasSystem() bool {
	if o != nil && o.System != nil {
		return true
	}

	return false
}

// SetSystem gets a reference to the given string and assigns it to the System field.
func (o *WealthWealthDistributionTotal) SetSystem(v string) {
	o.System = &v
}

// GetStake returns the Stake field value if set, zero value otherwise.
func (o *WealthWealthDistributionTotal) GetStake() string {
	if o == nil || o.Stake == nil {
		var ret string
		return ret
	}
	return *o.Stake
}

// GetStakeOk returns a tuple with the Stake field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WealthWealthDistributionTotal) GetStakeOk() (*string, bool) {
	if o == nil || o.Stake == nil {
		return nil, false
	}
	return o.Stake, true
}

// HasStake returns a boolean if a field has been set.
func (o *WealthWealthDistributionTotal) HasStake() bool {
	if o != nil && o.Stake != nil {
		return true
	}

	return false
}

// SetStake gets a reference to the given string and assigns it to the Stake field.
func (o *WealthWealthDistributionTotal) SetStake(v string) {
	o.Stake = &v
}

// GetSpl returns the Spl field value if set, zero value otherwise.
func (o *WealthWealthDistributionTotal) GetSpl() string {
	if o == nil || o.Spl == nil {
		var ret string
		return ret
	}
	return *o.Spl
}

// GetSplOk returns a tuple with the Spl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WealthWealthDistributionTotal) GetSplOk() (*string, bool) {
	if o == nil || o.Spl == nil {
		return nil, false
	}
	return o.Spl, true
}

// HasSpl returns a boolean if a field has been set.
func (o *WealthWealthDistributionTotal) HasSpl() bool {
	if o != nil && o.Spl != nil {
		return true
	}

	return false
}

// SetSpl gets a reference to the given string and assigns it to the Spl field.
func (o *WealthWealthDistributionTotal) SetSpl(v string) {
	o.Spl = &v
}

// GetSum returns the Sum field value if set, zero value otherwise.
func (o *WealthWealthDistributionTotal) GetSum() string {
	if o == nil || o.Sum == nil {
		var ret string
		return ret
	}
	return *o.Sum
}

// GetSumOk returns a tuple with the Sum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WealthWealthDistributionTotal) GetSumOk() (*string, bool) {
	if o == nil || o.Sum == nil {
		return nil, false
	}
	return o.Sum, true
}

// HasSum returns a boolean if a field has been set.
func (o *WealthWealthDistributionTotal) HasSum() bool {
	if o != nil && o.Sum != nil {
		return true
	}

	return false
}

// SetSum gets a reference to the given string and assigns it to the Sum field.
func (o *WealthWealthDistributionTotal) SetSum(v string) {
	o.Sum = &v
}

func (o WealthWealthDistributionTotal) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.System != nil {
		toSerialize["system"] = o.System
	}
	if o.Stake != nil {
		toSerialize["stake"] = o.Stake
	}
	if o.Spl != nil {
		toSerialize["spl"] = o.Spl
	}
	if o.Sum != nil {
		toSerialize["sum"] = o.Sum
	}
	return json.Marshal(toSerialize)
}

type NullableWealthWealthDistributionTotal struct {
	value *WealthWealthDistributionTotal
	isSet bool
}

func (v NullableWealthWealthDistributionTotal) Get() *WealthWealthDistributionTotal {
	return v.value
}

func (v *NullableWealthWealthDistributionTotal) Set(val *WealthWealthDistributionTotal) {
	v.value = val
	v.isSet = true
}

func (v NullableWealthWealthDistributionTotal) IsSet() bool {
	return v.isSet
}

func (v *NullableWealthWealthDistributionTotal) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWealthWealthDistributionTotal(val *WealthWealthDistributionTotal) *NullableWealthWealthDistributionTotal {
	return &NullableWealthWealthDistributionTotal{value: val, isSet: true}
}

func (v NullableWealthWealthDistributionTotal) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWealthWealthDistributionTotal) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


