/*
Solanabeach Backend API

Solanabeach Backend REST API documentation.  ## Rate limiting Current API rate limit per IP is 100 requests per second.    ## Pagination Most of the endpoints returning array data support pagination. The API uses two types of pagination, depending on the returned data. Some endpoints support both, some are limited to just one type.    ## Supported pagination types ### Offset / limit Offset / limit pagination is the simplest form of pagination supported by the API. Offset parameter represents the number of results to skip before returning the data, and the limit parameter limits the number of returned results.   To prevent overloading the API, all limit params have a max value. Each API endpoint has its own max value.  ### Cursor Cursor pagination is more complex than the offset / limit one, but, it comes naturally for some blockchain data (such as blocks, transactions, token transfers, etc). Cursors contain data like blocknumber, transaction index, ... and they're described on their respective API endpoints. Limit parameter works exactly the same way as it does in the offset / limit pagination.  ## Authentication The public API uses a Bearer OAuth authentication method, and the API key should be provided in the `Authorization` header in each request. API keys are issued on request. 

API version: 0.0.1
Contact: andrej@vgng.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// MarketMetaOrderBooks struct for MarketMetaOrderBooks
type MarketMetaOrderBooks struct {
	Asks *[][]float32 `json:"asks,omitempty"`
	Bids *[][]float32 `json:"bids,omitempty"`
}

// NewMarketMetaOrderBooks instantiates a new MarketMetaOrderBooks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMarketMetaOrderBooks() *MarketMetaOrderBooks {
	this := MarketMetaOrderBooks{}
	return &this
}

// NewMarketMetaOrderBooksWithDefaults instantiates a new MarketMetaOrderBooks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMarketMetaOrderBooksWithDefaults() *MarketMetaOrderBooks {
	this := MarketMetaOrderBooks{}
	return &this
}

// GetAsks returns the Asks field value if set, zero value otherwise.
func (o *MarketMetaOrderBooks) GetAsks() [][]float32 {
	if o == nil || o.Asks == nil {
		var ret [][]float32
		return ret
	}
	return *o.Asks
}

// GetAsksOk returns a tuple with the Asks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarketMetaOrderBooks) GetAsksOk() (*[][]float32, bool) {
	if o == nil || o.Asks == nil {
		return nil, false
	}
	return o.Asks, true
}

// HasAsks returns a boolean if a field has been set.
func (o *MarketMetaOrderBooks) HasAsks() bool {
	if o != nil && o.Asks != nil {
		return true
	}

	return false
}

// SetAsks gets a reference to the given [][]float32 and assigns it to the Asks field.
func (o *MarketMetaOrderBooks) SetAsks(v [][]float32) {
	o.Asks = &v
}

// GetBids returns the Bids field value if set, zero value otherwise.
func (o *MarketMetaOrderBooks) GetBids() [][]float32 {
	if o == nil || o.Bids == nil {
		var ret [][]float32
		return ret
	}
	return *o.Bids
}

// GetBidsOk returns a tuple with the Bids field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarketMetaOrderBooks) GetBidsOk() (*[][]float32, bool) {
	if o == nil || o.Bids == nil {
		return nil, false
	}
	return o.Bids, true
}

// HasBids returns a boolean if a field has been set.
func (o *MarketMetaOrderBooks) HasBids() bool {
	if o != nil && o.Bids != nil {
		return true
	}

	return false
}

// SetBids gets a reference to the given [][]float32 and assigns it to the Bids field.
func (o *MarketMetaOrderBooks) SetBids(v [][]float32) {
	o.Bids = &v
}

func (o MarketMetaOrderBooks) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Asks != nil {
		toSerialize["asks"] = o.Asks
	}
	if o.Bids != nil {
		toSerialize["bids"] = o.Bids
	}
	return json.Marshal(toSerialize)
}

type NullableMarketMetaOrderBooks struct {
	value *MarketMetaOrderBooks
	isSet bool
}

func (v NullableMarketMetaOrderBooks) Get() *MarketMetaOrderBooks {
	return v.value
}

func (v *NullableMarketMetaOrderBooks) Set(val *MarketMetaOrderBooks) {
	v.value = val
	v.isSet = true
}

func (v NullableMarketMetaOrderBooks) IsSet() bool {
	return v.isSet
}

func (v *NullableMarketMetaOrderBooks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMarketMetaOrderBooks(val *MarketMetaOrderBooks) *NullableMarketMetaOrderBooks {
	return &NullableMarketMetaOrderBooks{value: val, isSet: true}
}

func (v NullableMarketMetaOrderBooks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMarketMetaOrderBooks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


