/*
Solanabeach Backend API

Solanabeach Backend REST API documentation.  ## Rate limiting Current API rate limit per IP is 100 requests per second.    ## Pagination Most of the endpoints returning array data support pagination. The API uses two types of pagination, depending on the returned data. Some endpoints support both, some are limited to just one type.    ## Supported pagination types ### Offset / limit Offset / limit pagination is the simplest form of pagination supported by the API. Offset parameter represents the number of results to skip before returning the data, and the limit parameter limits the number of returned results.   To prevent overloading the API, all limit params have a max value. Each API endpoint has its own max value.  ### Cursor Cursor pagination is more complex than the offset / limit one, but, it comes naturally for some blockchain data (such as blocks, transactions, token transfers, etc). Cursors contain data like blocknumber, transaction index, ... and they're described on their respective API endpoints. Limit parameter works exactly the same way as it does in the offset / limit pagination.  ## Authentication The public API uses a Bearer OAuth authentication method, and the API key should be provided in the `Authorization` header in each request. API keys are issued on request. 

API version: 0.0.1
Contact: andrej@vgng.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// Timestamp struct for Timestamp
type Timestamp struct {
	Absolute *int32 `json:"absolute,omitempty"`
	Relative *int32 `json:"relative,omitempty"`
}

// NewTimestamp instantiates a new Timestamp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTimestamp() *Timestamp {
	this := Timestamp{}
	return &this
}

// NewTimestampWithDefaults instantiates a new Timestamp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTimestampWithDefaults() *Timestamp {
	this := Timestamp{}
	return &this
}

// GetAbsolute returns the Absolute field value if set, zero value otherwise.
func (o *Timestamp) GetAbsolute() int32 {
	if o == nil || o.Absolute == nil {
		var ret int32
		return ret
	}
	return *o.Absolute
}

// GetAbsoluteOk returns a tuple with the Absolute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Timestamp) GetAbsoluteOk() (*int32, bool) {
	if o == nil || o.Absolute == nil {
		return nil, false
	}
	return o.Absolute, true
}

// HasAbsolute returns a boolean if a field has been set.
func (o *Timestamp) HasAbsolute() bool {
	if o != nil && o.Absolute != nil {
		return true
	}

	return false
}

// SetAbsolute gets a reference to the given int32 and assigns it to the Absolute field.
func (o *Timestamp) SetAbsolute(v int32) {
	o.Absolute = &v
}

// GetRelative returns the Relative field value if set, zero value otherwise.
func (o *Timestamp) GetRelative() int32 {
	if o == nil || o.Relative == nil {
		var ret int32
		return ret
	}
	return *o.Relative
}

// GetRelativeOk returns a tuple with the Relative field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Timestamp) GetRelativeOk() (*int32, bool) {
	if o == nil || o.Relative == nil {
		return nil, false
	}
	return o.Relative, true
}

// HasRelative returns a boolean if a field has been set.
func (o *Timestamp) HasRelative() bool {
	if o != nil && o.Relative != nil {
		return true
	}

	return false
}

// SetRelative gets a reference to the given int32 and assigns it to the Relative field.
func (o *Timestamp) SetRelative(v int32) {
	o.Relative = &v
}

func (o Timestamp) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Absolute != nil {
		toSerialize["absolute"] = o.Absolute
	}
	if o.Relative != nil {
		toSerialize["relative"] = o.Relative
	}
	return json.Marshal(toSerialize)
}

type NullableTimestamp struct {
	value *Timestamp
	isSet bool
}

func (v NullableTimestamp) Get() *Timestamp {
	return v.value
}

func (v *NullableTimestamp) Set(val *Timestamp) {
	v.value = val
	v.isSet = true
}

func (v NullableTimestamp) IsSet() bool {
	return v.isSet
}

func (v *NullableTimestamp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTimestamp(val *Timestamp) *NullableTimestamp {
	return &NullableTimestamp{value: val, isSet: true}
}

func (v NullableTimestamp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTimestamp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


