/*
Solanabeach Backend API

Solanabeach Backend REST API documentation.  ## Rate limiting Current API rate limit per IP is 100 requests per second.    ## Pagination Most of the endpoints returning array data support pagination. The API uses two types of pagination, depending on the returned data. Some endpoints support both, some are limited to just one type.    ## Supported pagination types ### Offset / limit Offset / limit pagination is the simplest form of pagination supported by the API. Offset parameter represents the number of results to skip before returning the data, and the limit parameter limits the number of returned results.   To prevent overloading the API, all limit params have a max value. Each API endpoint has its own max value.  ### Cursor Cursor pagination is more complex than the offset / limit one, but, it comes naturally for some blockchain data (such as blocks, transactions, token transfers, etc). Cursors contain data like blocknumber, transaction index, ... and they're described on their respective API endpoints. Limit parameter works exactly the same way as it does in the offset / limit pagination.  ## Authentication The public API uses a Bearer OAuth authentication method, and the API key should be provided in the `Authorization` header in each request. API keys are issued on request. 

API version: 0.0.1
Contact: andrej@vgng.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// StakeAccountDataStake struct for StakeAccountDataStake
type StakeAccountDataStake struct {
	Delegation *StakeAccountDataStakeDelegation `json:"delegation,omitempty"`
	CreditsObserved *int32 `json:"credits_observed,omitempty"`
}

// NewStakeAccountDataStake instantiates a new StakeAccountDataStake object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStakeAccountDataStake() *StakeAccountDataStake {
	this := StakeAccountDataStake{}
	return &this
}

// NewStakeAccountDataStakeWithDefaults instantiates a new StakeAccountDataStake object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStakeAccountDataStakeWithDefaults() *StakeAccountDataStake {
	this := StakeAccountDataStake{}
	return &this
}

// GetDelegation returns the Delegation field value if set, zero value otherwise.
func (o *StakeAccountDataStake) GetDelegation() StakeAccountDataStakeDelegation {
	if o == nil || o.Delegation == nil {
		var ret StakeAccountDataStakeDelegation
		return ret
	}
	return *o.Delegation
}

// GetDelegationOk returns a tuple with the Delegation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StakeAccountDataStake) GetDelegationOk() (*StakeAccountDataStakeDelegation, bool) {
	if o == nil || o.Delegation == nil {
		return nil, false
	}
	return o.Delegation, true
}

// HasDelegation returns a boolean if a field has been set.
func (o *StakeAccountDataStake) HasDelegation() bool {
	if o != nil && o.Delegation != nil {
		return true
	}

	return false
}

// SetDelegation gets a reference to the given StakeAccountDataStakeDelegation and assigns it to the Delegation field.
func (o *StakeAccountDataStake) SetDelegation(v StakeAccountDataStakeDelegation) {
	o.Delegation = &v
}

// GetCreditsObserved returns the CreditsObserved field value if set, zero value otherwise.
func (o *StakeAccountDataStake) GetCreditsObserved() int32 {
	if o == nil || o.CreditsObserved == nil {
		var ret int32
		return ret
	}
	return *o.CreditsObserved
}

// GetCreditsObservedOk returns a tuple with the CreditsObserved field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StakeAccountDataStake) GetCreditsObservedOk() (*int32, bool) {
	if o == nil || o.CreditsObserved == nil {
		return nil, false
	}
	return o.CreditsObserved, true
}

// HasCreditsObserved returns a boolean if a field has been set.
func (o *StakeAccountDataStake) HasCreditsObserved() bool {
	if o != nil && o.CreditsObserved != nil {
		return true
	}

	return false
}

// SetCreditsObserved gets a reference to the given int32 and assigns it to the CreditsObserved field.
func (o *StakeAccountDataStake) SetCreditsObserved(v int32) {
	o.CreditsObserved = &v
}

func (o StakeAccountDataStake) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Delegation != nil {
		toSerialize["delegation"] = o.Delegation
	}
	if o.CreditsObserved != nil {
		toSerialize["credits_observed"] = o.CreditsObserved
	}
	return json.Marshal(toSerialize)
}

type NullableStakeAccountDataStake struct {
	value *StakeAccountDataStake
	isSet bool
}

func (v NullableStakeAccountDataStake) Get() *StakeAccountDataStake {
	return v.value
}

func (v *NullableStakeAccountDataStake) Set(val *StakeAccountDataStake) {
	v.value = val
	v.isSet = true
}

func (v NullableStakeAccountDataStake) IsSet() bool {
	return v.isSet
}

func (v *NullableStakeAccountDataStake) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStakeAccountDataStake(val *StakeAccountDataStake) *NullableStakeAccountDataStake {
	return &NullableStakeAccountDataStake{value: val, isSet: true}
}

func (v NullableStakeAccountDataStake) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStakeAccountDataStake) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


