/*
Solanabeach Backend API

Solanabeach Backend REST API documentation.  ## Rate limiting Current API rate limit per IP is 100 requests per second.    ## Pagination Most of the endpoints returning array data support pagination. The API uses two types of pagination, depending on the returned data. Some endpoints support both, some are limited to just one type.    ## Supported pagination types ### Offset / limit Offset / limit pagination is the simplest form of pagination supported by the API. Offset parameter represents the number of results to skip before returning the data, and the limit parameter limits the number of returned results.   To prevent overloading the API, all limit params have a max value. Each API endpoint has its own max value.  ### Cursor Cursor pagination is more complex than the offset / limit one, but, it comes naturally for some blockchain data (such as blocks, transactions, token transfers, etc). Cursors contain data like blocknumber, transaction index, ... and they're described on their respective API endpoints. Limit parameter works exactly the same way as it does in the offset / limit pagination.  ## Authentication The public API uses a Bearer OAuth authentication method, and the API key should be provided in the `Authorization` header in each request. API keys are issued on request. 

API version: 0.0.1
Contact: andrej@vgng.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// StakeAccountDataLockup struct for StakeAccountDataLockup
type StakeAccountDataLockup struct {
	UnixTimestamp *int32 `json:"unix_timestamp,omitempty"`
	Epoch *int32 `json:"epoch,omitempty"`
	Custodian *string `json:"custodian,omitempty"`
}

// NewStakeAccountDataLockup instantiates a new StakeAccountDataLockup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStakeAccountDataLockup() *StakeAccountDataLockup {
	this := StakeAccountDataLockup{}
	return &this
}

// NewStakeAccountDataLockupWithDefaults instantiates a new StakeAccountDataLockup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStakeAccountDataLockupWithDefaults() *StakeAccountDataLockup {
	this := StakeAccountDataLockup{}
	return &this
}

// GetUnixTimestamp returns the UnixTimestamp field value if set, zero value otherwise.
func (o *StakeAccountDataLockup) GetUnixTimestamp() int32 {
	if o == nil || o.UnixTimestamp == nil {
		var ret int32
		return ret
	}
	return *o.UnixTimestamp
}

// GetUnixTimestampOk returns a tuple with the UnixTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StakeAccountDataLockup) GetUnixTimestampOk() (*int32, bool) {
	if o == nil || o.UnixTimestamp == nil {
		return nil, false
	}
	return o.UnixTimestamp, true
}

// HasUnixTimestamp returns a boolean if a field has been set.
func (o *StakeAccountDataLockup) HasUnixTimestamp() bool {
	if o != nil && o.UnixTimestamp != nil {
		return true
	}

	return false
}

// SetUnixTimestamp gets a reference to the given int32 and assigns it to the UnixTimestamp field.
func (o *StakeAccountDataLockup) SetUnixTimestamp(v int32) {
	o.UnixTimestamp = &v
}

// GetEpoch returns the Epoch field value if set, zero value otherwise.
func (o *StakeAccountDataLockup) GetEpoch() int32 {
	if o == nil || o.Epoch == nil {
		var ret int32
		return ret
	}
	return *o.Epoch
}

// GetEpochOk returns a tuple with the Epoch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StakeAccountDataLockup) GetEpochOk() (*int32, bool) {
	if o == nil || o.Epoch == nil {
		return nil, false
	}
	return o.Epoch, true
}

// HasEpoch returns a boolean if a field has been set.
func (o *StakeAccountDataLockup) HasEpoch() bool {
	if o != nil && o.Epoch != nil {
		return true
	}

	return false
}

// SetEpoch gets a reference to the given int32 and assigns it to the Epoch field.
func (o *StakeAccountDataLockup) SetEpoch(v int32) {
	o.Epoch = &v
}

// GetCustodian returns the Custodian field value if set, zero value otherwise.
func (o *StakeAccountDataLockup) GetCustodian() string {
	if o == nil || o.Custodian == nil {
		var ret string
		return ret
	}
	return *o.Custodian
}

// GetCustodianOk returns a tuple with the Custodian field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StakeAccountDataLockup) GetCustodianOk() (*string, bool) {
	if o == nil || o.Custodian == nil {
		return nil, false
	}
	return o.Custodian, true
}

// HasCustodian returns a boolean if a field has been set.
func (o *StakeAccountDataLockup) HasCustodian() bool {
	if o != nil && o.Custodian != nil {
		return true
	}

	return false
}

// SetCustodian gets a reference to the given string and assigns it to the Custodian field.
func (o *StakeAccountDataLockup) SetCustodian(v string) {
	o.Custodian = &v
}

func (o StakeAccountDataLockup) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.UnixTimestamp != nil {
		toSerialize["unix_timestamp"] = o.UnixTimestamp
	}
	if o.Epoch != nil {
		toSerialize["epoch"] = o.Epoch
	}
	if o.Custodian != nil {
		toSerialize["custodian"] = o.Custodian
	}
	return json.Marshal(toSerialize)
}

type NullableStakeAccountDataLockup struct {
	value *StakeAccountDataLockup
	isSet bool
}

func (v NullableStakeAccountDataLockup) Get() *StakeAccountDataLockup {
	return v.value
}

func (v *NullableStakeAccountDataLockup) Set(val *StakeAccountDataLockup) {
	v.value = val
	v.isSet = true
}

func (v NullableStakeAccountDataLockup) IsSet() bool {
	return v.isSet
}

func (v *NullableStakeAccountDataLockup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStakeAccountDataLockup(val *StakeAccountDataLockup) *NullableStakeAccountDataLockup {
	return &NullableStakeAccountDataLockup{value: val, isSet: true}
}

func (v NullableStakeAccountDataLockup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStakeAccountDataLockup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


