/*
Solanabeach Backend API

Solanabeach Backend REST API documentation.  ## Rate limiting Current API rate limit per IP is 100 requests per second.    ## Pagination Most of the endpoints returning array data support pagination. The API uses two types of pagination, depending on the returned data. Some endpoints support both, some are limited to just one type.    ## Supported pagination types ### Offset / limit Offset / limit pagination is the simplest form of pagination supported by the API. Offset parameter represents the number of results to skip before returning the data, and the limit parameter limits the number of returned results.   To prevent overloading the API, all limit params have a max value. Each API endpoint has its own max value.  ### Cursor Cursor pagination is more complex than the offset / limit one, but, it comes naturally for some blockchain data (such as blocks, transactions, token transfers, etc). Cursors contain data like blocknumber, transaction index, ... and they're described on their respective API endpoints. Limit parameter works exactly the same way as it does in the offset / limit pagination.  ## Authentication The public API uses a Bearer OAuth authentication method, and the API key should be provided in the `Authorization` header in each request. API keys are issued on request. 

API version: 0.0.1
Contact: andrej@vgng.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ValidatorHistoric struct for ValidatorHistoric
type ValidatorHistoric struct {
	Stake *int32 `json:"stake,omitempty"`
	Delegators *int32 `json:"delegators,omitempty"`
	Timestamp *string `json:"timestamp,omitempty"`
}

// NewValidatorHistoric instantiates a new ValidatorHistoric object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValidatorHistoric() *ValidatorHistoric {
	this := ValidatorHistoric{}
	return &this
}

// NewValidatorHistoricWithDefaults instantiates a new ValidatorHistoric object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValidatorHistoricWithDefaults() *ValidatorHistoric {
	this := ValidatorHistoric{}
	return &this
}

// GetStake returns the Stake field value if set, zero value otherwise.
func (o *ValidatorHistoric) GetStake() int32 {
	if o == nil || o.Stake == nil {
		var ret int32
		return ret
	}
	return *o.Stake
}

// GetStakeOk returns a tuple with the Stake field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidatorHistoric) GetStakeOk() (*int32, bool) {
	if o == nil || o.Stake == nil {
		return nil, false
	}
	return o.Stake, true
}

// HasStake returns a boolean if a field has been set.
func (o *ValidatorHistoric) HasStake() bool {
	if o != nil && o.Stake != nil {
		return true
	}

	return false
}

// SetStake gets a reference to the given int32 and assigns it to the Stake field.
func (o *ValidatorHistoric) SetStake(v int32) {
	o.Stake = &v
}

// GetDelegators returns the Delegators field value if set, zero value otherwise.
func (o *ValidatorHistoric) GetDelegators() int32 {
	if o == nil || o.Delegators == nil {
		var ret int32
		return ret
	}
	return *o.Delegators
}

// GetDelegatorsOk returns a tuple with the Delegators field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidatorHistoric) GetDelegatorsOk() (*int32, bool) {
	if o == nil || o.Delegators == nil {
		return nil, false
	}
	return o.Delegators, true
}

// HasDelegators returns a boolean if a field has been set.
func (o *ValidatorHistoric) HasDelegators() bool {
	if o != nil && o.Delegators != nil {
		return true
	}

	return false
}

// SetDelegators gets a reference to the given int32 and assigns it to the Delegators field.
func (o *ValidatorHistoric) SetDelegators(v int32) {
	o.Delegators = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *ValidatorHistoric) GetTimestamp() string {
	if o == nil || o.Timestamp == nil {
		var ret string
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidatorHistoric) GetTimestampOk() (*string, bool) {
	if o == nil || o.Timestamp == nil {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *ValidatorHistoric) HasTimestamp() bool {
	if o != nil && o.Timestamp != nil {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given string and assigns it to the Timestamp field.
func (o *ValidatorHistoric) SetTimestamp(v string) {
	o.Timestamp = &v
}

func (o ValidatorHistoric) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Stake != nil {
		toSerialize["stake"] = o.Stake
	}
	if o.Delegators != nil {
		toSerialize["delegators"] = o.Delegators
	}
	if o.Timestamp != nil {
		toSerialize["timestamp"] = o.Timestamp
	}
	return json.Marshal(toSerialize)
}

type NullableValidatorHistoric struct {
	value *ValidatorHistoric
	isSet bool
}

func (v NullableValidatorHistoric) Get() *ValidatorHistoric {
	return v.value
}

func (v *NullableValidatorHistoric) Set(val *ValidatorHistoric) {
	v.value = val
	v.isSet = true
}

func (v NullableValidatorHistoric) IsSet() bool {
	return v.isSet
}

func (v *NullableValidatorHistoric) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValidatorHistoric(val *ValidatorHistoric) *NullableValidatorHistoric {
	return &NullableValidatorHistoric{value: val, isSet: true}
}

func (v NullableValidatorHistoric) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValidatorHistoric) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


